package telegram

import (
	"encoding/json"
	"fmt"
	"github.com/kz2d/telegram-bot/pkg/database"
	"io"
	"net/http"
	"time"
)

func Start(callback func(Message)) {
	url := fmt.Sprintf("https://api.telegram.org/bot%s/getUpdates", client.token)
	cl := http.Client{Timeout: 3 * time.Second}

	var lastId int64 = database.GetLastActiviti()

	for {
		time.Sleep(1 * time.Second)

		res, err := cl.Get(url)
		if err != nil {
			fmt.Println("telegram request error", err)
			continue
		}

		body, err := io.ReadAll(res.Body)

		if err != nil {
			fmt.Println(err)
			continue
		}

		update := AutoGenerated{}
		err = json.Unmarshal(body, &update)
		if err != nil {
			fmt.Println(err)
			return
		}

		if update.Ok {
			for _, u := range update.Result {
				if lastId < u.UpdateID {
					lastId = u.UpdateID

					go callback(u.Message)
				}
			}
		}
		database.SetLastActiviti(lastId)
	}

}
