package config

import (
	"github.com/ghodss/yaml"
	"io"
	"os"
)

type AutoGenerated struct {
	Telegram struct {
		Token string `yaml:"token"`
	} `yaml:"telegram"`
	Database struct {
		Host     string `yaml:"host"`
		Port     int    `yaml:"port"`
		Dbname   string `yaml:"dbname"`
		User     string `yaml:"user"`
		Password string `yaml:"password"`
	} `yaml:"database"`
}

func Load(path string) (AutoGenerated, error) {
	file, err := os.Open(path)
	if err != nil {
		return AutoGenerated{}, err
	}
	bytes, err := io.ReadAll(file)
	if err != nil {
		return AutoGenerated{}, err
	}
	var config AutoGenerated
	err = yaml.Unmarshal(bytes, &config)
	return config, err
}
